name: Jest

on:
  pull_request:
    branches:
      - legacy

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout PR
        uses: actions/checkout@v1

      - name: Specify node version
        uses: actions/setup-node@v1
        with:
          node-version: '8.16.0'

      - name: Cache depedendencies
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/node_modules
          ## Check cache based on yarn.lock hashfile
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        ## If no cache is found, install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

  test:
    name: Test
    needs: [setup]
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout PR
        uses: actions/checkout@v1
      - name: Lint
        run: yarn tslint
      - name: TScheck
        run: yarn tscheck
      - name: Test
        run: yarn test:coverage
      - name: Report
        run: yarn report-coverage
